language: node_js
node_js:
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directory:
    - $HOME/.yarn/bin
jobs:
  include:
    - stage: lint
      script: yarn workspace shared lint
      name: lint shared
    - script: yarn workspace client lint
      name: lint client
    - script: yarn workspace server lint
      name: lint server
    - stage: build and test
      script: yarn build-test
    - stage: deploy
      script: yarn deploy
stages:
  - lint
  - build and test
  - name: deploy
    if: branch = master
