language: node_js
node_js:
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directory:
    - $HOME/.yarn/bin
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: build
      script: yarn build
