language: node_js
node_js:
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directory:
    - $HOME/.yarn/bin
jobs:
  include:
    - stage: lint
      script: yarn workspace shared lint
      name: lint shared
    - script: yarn workspace client lint
      name: lint client
    - script: yarn workspace server lint
      name: lint server
    - stage: build shared
      script: yarn workspace shared build
    - stage: build
      script: yarn workspace client build
      name: build client
    - script: yarn workspace server build
      name: build server
    - stage: test
      script: yarn workspace server test
    - stage: deploy
      script: yarn deploy
stages:
  - lint
  - build shared
  - build
  - test
  - name: deploy
    if: branch = master
