import { ModelService } from 'shared';
import { GameService, HTTPService, PlayerService, RoomService, SocketService } from './services';
export declare const httpService: HTTPService;
export declare const socketService: SocketService;
export declare const modelService: ModelService;
export declare const playerService: PlayerService;
export declare const roomService: RoomService;
export declare const gameService: GameService;
export declare const servicesReady: Promise<never[]>;
export declare function listen(): void;
